### PR TITLE
add missing dependency

### PR DESCRIPTION
**Pull request by aremazeilles**

### CODE REVIEW

**Comment by dborro** [comment]
It's done.

**Comment by aremazeilles** [comment]
Not sure what you mean by `done`. 
If you look above at the Files changed, you will see the change I had to do. 
If you accept that Merge Request (Button Merge Pull Request) the branch will be merged with `main`.

**Comment by dborro** [comment]
Sorry, I wanted to say that everything seems fine.
I will close this branch.

**Comment by aremazeilles** [comment]
You should reopen it, and Press the Button Merge Pull REquest.
Otherwise the proposed change is not brought to `main`

**Pull request merged**
